#!/bin/bash 

PERFORMANCE_DIR="${HOME}/performance"

if [[ -d "${PERFORMANCE_DIR}" ]]
then 
 echo "Directory ${PERFORMANCE_DIR} already exists"
else
 mkdir ${HOME}/performance
fi 

free >> ${PERFORMANCE_DIR}/memory.log 
 
